// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_stat.proto

package org.frozen.pb;

public final class ObjectStat {
  private ObjectStat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DimensionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string c1 = 1;
    /**
     * <code>optional string c1 = 1;</code>
     */
    boolean hasC1();
    /**
     * <code>optional string c1 = 1;</code>
     */
    java.lang.String getC1();
    /**
     * <code>optional string c1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getC1Bytes();

    // optional string c2 = 2;
    /**
     * <code>optional string c2 = 2;</code>
     */
    boolean hasC2();
    /**
     * <code>optional string c2 = 2;</code>
     */
    java.lang.String getC2();
    /**
     * <code>optional string c2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getC2Bytes();

    // optional string c3 = 3;
    /**
     * <code>optional string c3 = 3;</code>
     */
    boolean hasC3();
    /**
     * <code>optional string c3 = 3;</code>
     */
    java.lang.String getC3();
    /**
     * <code>optional string c3 = 3;</code>
     */
    com.google.protobuf.ByteString
        getC3Bytes();

    // optional string c4 = 4;
    /**
     * <code>optional string c4 = 4;</code>
     */
    boolean hasC4();
    /**
     * <code>optional string c4 = 4;</code>
     */
    java.lang.String getC4();
    /**
     * <code>optional string c4 = 4;</code>
     */
    com.google.protobuf.ByteString
        getC4Bytes();

    // optional string c5 = 5;
    /**
     * <code>optional string c5 = 5;</code>
     */
    boolean hasC5();
    /**
     * <code>optional string c5 = 5;</code>
     */
    java.lang.String getC5();
    /**
     * <code>optional string c5 = 5;</code>
     */
    com.google.protobuf.ByteString
        getC5Bytes();

    // optional string c6 = 6;
    /**
     * <code>optional string c6 = 6;</code>
     */
    boolean hasC6();
    /**
     * <code>optional string c6 = 6;</code>
     */
    java.lang.String getC6();
    /**
     * <code>optional string c6 = 6;</code>
     */
    com.google.protobuf.ByteString
        getC6Bytes();

    // optional string c7 = 7;
    /**
     * <code>optional string c7 = 7;</code>
     */
    boolean hasC7();
    /**
     * <code>optional string c7 = 7;</code>
     */
    java.lang.String getC7();
    /**
     * <code>optional string c7 = 7;</code>
     */
    com.google.protobuf.ByteString
        getC7Bytes();

    // optional string c8 = 8;
    /**
     * <code>optional string c8 = 8;</code>
     */
    boolean hasC8();
    /**
     * <code>optional string c8 = 8;</code>
     */
    java.lang.String getC8();
    /**
     * <code>optional string c8 = 8;</code>
     */
    com.google.protobuf.ByteString
        getC8Bytes();

    // optional string c9 = 9;
    /**
     * <code>optional string c9 = 9;</code>
     */
    boolean hasC9();
    /**
     * <code>optional string c9 = 9;</code>
     */
    java.lang.String getC9();
    /**
     * <code>optional string c9 = 9;</code>
     */
    com.google.protobuf.ByteString
        getC9Bytes();

    // optional string c10 = 10;
    /**
     * <code>optional string c10 = 10;</code>
     */
    boolean hasC10();
    /**
     * <code>optional string c10 = 10;</code>
     */
    java.lang.String getC10();
    /**
     * <code>optional string c10 = 10;</code>
     */
    com.google.protobuf.ByteString
        getC10Bytes();

    // optional string stat_id = 14;
    /**
     * <code>optional string stat_id = 14;</code>
     *
     * <pre>
     *统计标识
     * </pre>
     */
    boolean hasStatId();
    /**
     * <code>optional string stat_id = 14;</code>
     *
     * <pre>
     *统计标识
     * </pre>
     */
    java.lang.String getStatId();
    /**
     * <code>optional string stat_id = 14;</code>
     *
     * <pre>
     *统计标识
     * </pre>
     */
    com.google.protobuf.ByteString
        getStatIdBytes();

    // optional int64 timekey = 15;
    /**
     * <code>optional int64 timekey = 15;</code>
     *
     * <pre>
     *统计时间: 绝对秒数
     * </pre>
     */
    boolean hasTimekey();
    /**
     * <code>optional int64 timekey = 15;</code>
     *
     * <pre>
     *统计时间: 绝对秒数
     * </pre>
     */
    long getTimekey();
  }
  /**
   * Protobuf type {@code org.frozen.pb.Dimensions}
   *
   * <pre>
   *统计维度(用于计算MD5，由对象多个不同属性组成，最多支持10个，每个属性的位置序号由对象统计策略定义)
   * </pre>
   */
  public static final class Dimensions extends
      com.google.protobuf.GeneratedMessage
      implements DimensionsOrBuilder {
    // Use Dimensions.newBuilder() to construct.
    private Dimensions(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Dimensions(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Dimensions defaultInstance;
    public static Dimensions getDefaultInstance() {
      return defaultInstance;
    }

    public Dimensions getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Dimensions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              c1_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              c2_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              c3_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              c4_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              c5_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              c6_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              c7_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              c8_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              c9_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              c10_ = input.readBytes();
              break;
            }
            case 114: {
              bitField0_ |= 0x00000400;
              statId_ = input.readBytes();
              break;
            }
            case 120: {
              bitField0_ |= 0x00000800;
              timekey_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.frozen.pb.ObjectStat.internal_static_pb_ayena_Dimensions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.frozen.pb.ObjectStat.internal_static_pb_ayena_Dimensions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.frozen.pb.ObjectStat.Dimensions.class, org.frozen.pb.ObjectStat.Dimensions.Builder.class);
    }

    public static com.google.protobuf.Parser<Dimensions> PARSER =
        new com.google.protobuf.AbstractParser<Dimensions>() {
      public Dimensions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dimensions(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Dimensions> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string c1 = 1;
    public static final int C1_FIELD_NUMBER = 1;
    private java.lang.Object c1_;
    /**
     * <code>optional string c1 = 1;</code>
     */
    public boolean hasC1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string c1 = 1;</code>
     */
    public java.lang.String getC1() {
      java.lang.Object ref = c1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getC1Bytes() {
      java.lang.Object ref = c1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string c2 = 2;
    public static final int C2_FIELD_NUMBER = 2;
    private java.lang.Object c2_;
    /**
     * <code>optional string c2 = 2;</code>
     */
    public boolean hasC2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string c2 = 2;</code>
     */
    public java.lang.String getC2() {
      java.lang.Object ref = c2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c2_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getC2Bytes() {
      java.lang.Object ref = c2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string c3 = 3;
    public static final int C3_FIELD_NUMBER = 3;
    private java.lang.Object c3_;
    /**
     * <code>optional string c3 = 3;</code>
     */
    public boolean hasC3() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string c3 = 3;</code>
     */
    public java.lang.String getC3() {
      java.lang.Object ref = c3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c3_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c3 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getC3Bytes() {
      java.lang.Object ref = c3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string c4 = 4;
    public static final int C4_FIELD_NUMBER = 4;
    private java.lang.Object c4_;
    /**
     * <code>optional string c4 = 4;</code>
     */
    public boolean hasC4() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string c4 = 4;</code>
     */
    public java.lang.String getC4() {
      java.lang.Object ref = c4_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c4_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c4 = 4;</code>
     */
    public com.google.protobuf.ByteString
        getC4Bytes() {
      java.lang.Object ref = c4_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string c5 = 5;
    public static final int C5_FIELD_NUMBER = 5;
    private java.lang.Object c5_;
    /**
     * <code>optional string c5 = 5;</code>
     */
    public boolean hasC5() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string c5 = 5;</code>
     */
    public java.lang.String getC5() {
      java.lang.Object ref = c5_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c5_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c5 = 5;</code>
     */
    public com.google.protobuf.ByteString
        getC5Bytes() {
      java.lang.Object ref = c5_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string c6 = 6;
    public static final int C6_FIELD_NUMBER = 6;
    private java.lang.Object c6_;
    /**
     * <code>optional string c6 = 6;</code>
     */
    public boolean hasC6() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string c6 = 6;</code>
     */
    public java.lang.String getC6() {
      java.lang.Object ref = c6_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c6_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c6 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getC6Bytes() {
      java.lang.Object ref = c6_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c6_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string c7 = 7;
    public static final int C7_FIELD_NUMBER = 7;
    private java.lang.Object c7_;
    /**
     * <code>optional string c7 = 7;</code>
     */
    public boolean hasC7() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string c7 = 7;</code>
     */
    public java.lang.String getC7() {
      java.lang.Object ref = c7_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c7_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c7 = 7;</code>
     */
    public com.google.protobuf.ByteString
        getC7Bytes() {
      java.lang.Object ref = c7_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c7_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string c8 = 8;
    public static final int C8_FIELD_NUMBER = 8;
    private java.lang.Object c8_;
    /**
     * <code>optional string c8 = 8;</code>
     */
    public boolean hasC8() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string c8 = 8;</code>
     */
    public java.lang.String getC8() {
      java.lang.Object ref = c8_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c8_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c8 = 8;</code>
     */
    public com.google.protobuf.ByteString
        getC8Bytes() {
      java.lang.Object ref = c8_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c8_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string c9 = 9;
    public static final int C9_FIELD_NUMBER = 9;
    private java.lang.Object c9_;
    /**
     * <code>optional string c9 = 9;</code>
     */
    public boolean hasC9() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string c9 = 9;</code>
     */
    public java.lang.String getC9() {
      java.lang.Object ref = c9_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c9_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c9 = 9;</code>
     */
    public com.google.protobuf.ByteString
        getC9Bytes() {
      java.lang.Object ref = c9_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c9_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string c10 = 10;
    public static final int C10_FIELD_NUMBER = 10;
    private java.lang.Object c10_;
    /**
     * <code>optional string c10 = 10;</code>
     */
    public boolean hasC10() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string c10 = 10;</code>
     */
    public java.lang.String getC10() {
      java.lang.Object ref = c10_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c10_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string c10 = 10;</code>
     */
    public com.google.protobuf.ByteString
        getC10Bytes() {
      java.lang.Object ref = c10_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c10_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string stat_id = 14;
    public static final int STAT_ID_FIELD_NUMBER = 14;
    private java.lang.Object statId_;
    /**
     * <code>optional string stat_id = 14;</code>
     *
     * <pre>
     *统计标识
     * </pre>
     */
    public boolean hasStatId() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string stat_id = 14;</code>
     *
     * <pre>
     *统计标识
     * </pre>
     */
    public java.lang.String getStatId() {
      java.lang.Object ref = statId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          statId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stat_id = 14;</code>
     *
     * <pre>
     *统计标识
     * </pre>
     */
    public com.google.protobuf.ByteString
        getStatIdBytes() {
      java.lang.Object ref = statId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 timekey = 15;
    public static final int TIMEKEY_FIELD_NUMBER = 15;
    private long timekey_;
    /**
     * <code>optional int64 timekey = 15;</code>
     *
     * <pre>
     *统计时间: 绝对秒数
     * </pre>
     */
    public boolean hasTimekey() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int64 timekey = 15;</code>
     *
     * <pre>
     *统计时间: 绝对秒数
     * </pre>
     */
    public long getTimekey() {
      return timekey_;
    }

    private void initFields() {
      c1_ = "";
      c2_ = "";
      c3_ = "";
      c4_ = "";
      c5_ = "";
      c6_ = "";
      c7_ = "";
      c8_ = "";
      c9_ = "";
      c10_ = "";
      statId_ = "";
      timekey_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getC1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getC2Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getC3Bytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getC4Bytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getC5Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getC6Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getC7Bytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getC8Bytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getC9Bytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getC10Bytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(14, getStatIdBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt64(15, timekey_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getC1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getC2Bytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getC3Bytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getC4Bytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getC5Bytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getC6Bytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getC7Bytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getC8Bytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getC9Bytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getC10Bytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getStatIdBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(15, timekey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.frozen.pb.ObjectStat.Dimensions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.frozen.pb.ObjectStat.Dimensions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.frozen.pb.ObjectStat.Dimensions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.frozen.pb.ObjectStat.Dimensions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.frozen.pb.ObjectStat.Dimensions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.frozen.pb.ObjectStat.Dimensions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.frozen.pb.ObjectStat.Dimensions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.frozen.pb.ObjectStat.Dimensions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.frozen.pb.ObjectStat.Dimensions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.frozen.pb.ObjectStat.Dimensions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.frozen.pb.ObjectStat.Dimensions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.frozen.pb.Dimensions}
     *
     * <pre>
     *统计维度(用于计算MD5，由对象多个不同属性组成，最多支持10个，每个属性的位置序号由对象统计策略定义)
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.frozen.pb.ObjectStat.DimensionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.frozen.pb.ObjectStat.internal_static_pb_ayena_Dimensions_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.frozen.pb.ObjectStat.internal_static_pb_ayena_Dimensions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.frozen.pb.ObjectStat.Dimensions.class, org.frozen.pb.ObjectStat.Dimensions.Builder.class);
      }

      // Construct using org.frozen.pb.ObjectStat.Dimensions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        c1_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        c2_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        c3_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        c4_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        c5_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        c6_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        c7_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        c8_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        c9_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        c10_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        statId_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        timekey_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.frozen.pb.ObjectStat.internal_static_pb_ayena_Dimensions_descriptor;
      }

      public org.frozen.pb.ObjectStat.Dimensions getDefaultInstanceForType() {
        return org.frozen.pb.ObjectStat.Dimensions.getDefaultInstance();
      }

      public org.frozen.pb.ObjectStat.Dimensions build() {
        org.frozen.pb.ObjectStat.Dimensions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.frozen.pb.ObjectStat.Dimensions buildPartial() {
        org.frozen.pb.ObjectStat.Dimensions result = new org.frozen.pb.ObjectStat.Dimensions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.c1_ = c1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.c2_ = c2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.c3_ = c3_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.c4_ = c4_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.c5_ = c5_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.c6_ = c6_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.c7_ = c7_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.c8_ = c8_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.c9_ = c9_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.c10_ = c10_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.statId_ = statId_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.timekey_ = timekey_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.frozen.pb.ObjectStat.Dimensions) {
          return mergeFrom((org.frozen.pb.ObjectStat.Dimensions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.frozen.pb.ObjectStat.Dimensions other) {
        if (other == org.frozen.pb.ObjectStat.Dimensions.getDefaultInstance()) return this;
        if (other.hasC1()) {
          bitField0_ |= 0x00000001;
          c1_ = other.c1_;
          onChanged();
        }
        if (other.hasC2()) {
          bitField0_ |= 0x00000002;
          c2_ = other.c2_;
          onChanged();
        }
        if (other.hasC3()) {
          bitField0_ |= 0x00000004;
          c3_ = other.c3_;
          onChanged();
        }
        if (other.hasC4()) {
          bitField0_ |= 0x00000008;
          c4_ = other.c4_;
          onChanged();
        }
        if (other.hasC5()) {
          bitField0_ |= 0x00000010;
          c5_ = other.c5_;
          onChanged();
        }
        if (other.hasC6()) {
          bitField0_ |= 0x00000020;
          c6_ = other.c6_;
          onChanged();
        }
        if (other.hasC7()) {
          bitField0_ |= 0x00000040;
          c7_ = other.c7_;
          onChanged();
        }
        if (other.hasC8()) {
          bitField0_ |= 0x00000080;
          c8_ = other.c8_;
          onChanged();
        }
        if (other.hasC9()) {
          bitField0_ |= 0x00000100;
          c9_ = other.c9_;
          onChanged();
        }
        if (other.hasC10()) {
          bitField0_ |= 0x00000200;
          c10_ = other.c10_;
          onChanged();
        }
        if (other.hasStatId()) {
          bitField0_ |= 0x00000400;
          statId_ = other.statId_;
          onChanged();
        }
        if (other.hasTimekey()) {
          setTimekey(other.getTimekey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.frozen.pb.ObjectStat.Dimensions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.frozen.pb.ObjectStat.Dimensions) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string c1 = 1;
      private java.lang.Object c1_ = "";
      /**
       * <code>optional string c1 = 1;</code>
       */
      public boolean hasC1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string c1 = 1;</code>
       */
      public java.lang.String getC1() {
        java.lang.Object ref = c1_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getC1Bytes() {
        java.lang.Object ref = c1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c1 = 1;</code>
       */
      public Builder setC1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        c1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c1 = 1;</code>
       */
      public Builder clearC1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        c1_ = getDefaultInstance().getC1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c1 = 1;</code>
       */
      public Builder setC1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        c1_ = value;
        onChanged();
        return this;
      }

      // optional string c2 = 2;
      private java.lang.Object c2_ = "";
      /**
       * <code>optional string c2 = 2;</code>
       */
      public boolean hasC2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string c2 = 2;</code>
       */
      public java.lang.String getC2() {
        java.lang.Object ref = c2_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getC2Bytes() {
        java.lang.Object ref = c2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c2 = 2;</code>
       */
      public Builder setC2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        c2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c2 = 2;</code>
       */
      public Builder clearC2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        c2_ = getDefaultInstance().getC2();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c2 = 2;</code>
       */
      public Builder setC2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        c2_ = value;
        onChanged();
        return this;
      }

      // optional string c3 = 3;
      private java.lang.Object c3_ = "";
      /**
       * <code>optional string c3 = 3;</code>
       */
      public boolean hasC3() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string c3 = 3;</code>
       */
      public java.lang.String getC3() {
        java.lang.Object ref = c3_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c3_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c3 = 3;</code>
       */
      public com.google.protobuf.ByteString
          getC3Bytes() {
        java.lang.Object ref = c3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c3 = 3;</code>
       */
      public Builder setC3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        c3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c3 = 3;</code>
       */
      public Builder clearC3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        c3_ = getDefaultInstance().getC3();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c3 = 3;</code>
       */
      public Builder setC3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        c3_ = value;
        onChanged();
        return this;
      }

      // optional string c4 = 4;
      private java.lang.Object c4_ = "";
      /**
       * <code>optional string c4 = 4;</code>
       */
      public boolean hasC4() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string c4 = 4;</code>
       */
      public java.lang.String getC4() {
        java.lang.Object ref = c4_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c4_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c4 = 4;</code>
       */
      public com.google.protobuf.ByteString
          getC4Bytes() {
        java.lang.Object ref = c4_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c4_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c4 = 4;</code>
       */
      public Builder setC4(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        c4_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c4 = 4;</code>
       */
      public Builder clearC4() {
        bitField0_ = (bitField0_ & ~0x00000008);
        c4_ = getDefaultInstance().getC4();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c4 = 4;</code>
       */
      public Builder setC4Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        c4_ = value;
        onChanged();
        return this;
      }

      // optional string c5 = 5;
      private java.lang.Object c5_ = "";
      /**
       * <code>optional string c5 = 5;</code>
       */
      public boolean hasC5() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string c5 = 5;</code>
       */
      public java.lang.String getC5() {
        java.lang.Object ref = c5_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c5_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c5 = 5;</code>
       */
      public com.google.protobuf.ByteString
          getC5Bytes() {
        java.lang.Object ref = c5_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c5_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c5 = 5;</code>
       */
      public Builder setC5(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        c5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c5 = 5;</code>
       */
      public Builder clearC5() {
        bitField0_ = (bitField0_ & ~0x00000010);
        c5_ = getDefaultInstance().getC5();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c5 = 5;</code>
       */
      public Builder setC5Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        c5_ = value;
        onChanged();
        return this;
      }

      // optional string c6 = 6;
      private java.lang.Object c6_ = "";
      /**
       * <code>optional string c6 = 6;</code>
       */
      public boolean hasC6() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string c6 = 6;</code>
       */
      public java.lang.String getC6() {
        java.lang.Object ref = c6_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c6_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c6 = 6;</code>
       */
      public com.google.protobuf.ByteString
          getC6Bytes() {
        java.lang.Object ref = c6_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c6_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c6 = 6;</code>
       */
      public Builder setC6(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        c6_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c6 = 6;</code>
       */
      public Builder clearC6() {
        bitField0_ = (bitField0_ & ~0x00000020);
        c6_ = getDefaultInstance().getC6();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c6 = 6;</code>
       */
      public Builder setC6Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        c6_ = value;
        onChanged();
        return this;
      }

      // optional string c7 = 7;
      private java.lang.Object c7_ = "";
      /**
       * <code>optional string c7 = 7;</code>
       */
      public boolean hasC7() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string c7 = 7;</code>
       */
      public java.lang.String getC7() {
        java.lang.Object ref = c7_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c7_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c7 = 7;</code>
       */
      public com.google.protobuf.ByteString
          getC7Bytes() {
        java.lang.Object ref = c7_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c7_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c7 = 7;</code>
       */
      public Builder setC7(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        c7_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c7 = 7;</code>
       */
      public Builder clearC7() {
        bitField0_ = (bitField0_ & ~0x00000040);
        c7_ = getDefaultInstance().getC7();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c7 = 7;</code>
       */
      public Builder setC7Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        c7_ = value;
        onChanged();
        return this;
      }

      // optional string c8 = 8;
      private java.lang.Object c8_ = "";
      /**
       * <code>optional string c8 = 8;</code>
       */
      public boolean hasC8() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string c8 = 8;</code>
       */
      public java.lang.String getC8() {
        java.lang.Object ref = c8_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c8_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c8 = 8;</code>
       */
      public com.google.protobuf.ByteString
          getC8Bytes() {
        java.lang.Object ref = c8_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c8_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c8 = 8;</code>
       */
      public Builder setC8(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        c8_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c8 = 8;</code>
       */
      public Builder clearC8() {
        bitField0_ = (bitField0_ & ~0x00000080);
        c8_ = getDefaultInstance().getC8();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c8 = 8;</code>
       */
      public Builder setC8Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        c8_ = value;
        onChanged();
        return this;
      }

      // optional string c9 = 9;
      private java.lang.Object c9_ = "";
      /**
       * <code>optional string c9 = 9;</code>
       */
      public boolean hasC9() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string c9 = 9;</code>
       */
      public java.lang.String getC9() {
        java.lang.Object ref = c9_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c9_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c9 = 9;</code>
       */
      public com.google.protobuf.ByteString
          getC9Bytes() {
        java.lang.Object ref = c9_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c9_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c9 = 9;</code>
       */
      public Builder setC9(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        c9_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c9 = 9;</code>
       */
      public Builder clearC9() {
        bitField0_ = (bitField0_ & ~0x00000100);
        c9_ = getDefaultInstance().getC9();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c9 = 9;</code>
       */
      public Builder setC9Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        c9_ = value;
        onChanged();
        return this;
      }

      // optional string c10 = 10;
      private java.lang.Object c10_ = "";
      /**
       * <code>optional string c10 = 10;</code>
       */
      public boolean hasC10() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string c10 = 10;</code>
       */
      public java.lang.String getC10() {
        java.lang.Object ref = c10_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          c10_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string c10 = 10;</code>
       */
      public com.google.protobuf.ByteString
          getC10Bytes() {
        java.lang.Object ref = c10_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c10_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string c10 = 10;</code>
       */
      public Builder setC10(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        c10_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string c10 = 10;</code>
       */
      public Builder clearC10() {
        bitField0_ = (bitField0_ & ~0x00000200);
        c10_ = getDefaultInstance().getC10();
        onChanged();
        return this;
      }
      /**
       * <code>optional string c10 = 10;</code>
       */
      public Builder setC10Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        c10_ = value;
        onChanged();
        return this;
      }

      // optional string stat_id = 14;
      private java.lang.Object statId_ = "";
      /**
       * <code>optional string stat_id = 14;</code>
       *
       * <pre>
       *统计标识
       * </pre>
       */
      public boolean hasStatId() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string stat_id = 14;</code>
       *
       * <pre>
       *统计标识
       * </pre>
       */
      public java.lang.String getStatId() {
        java.lang.Object ref = statId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          statId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string stat_id = 14;</code>
       *
       * <pre>
       *统计标识
       * </pre>
       */
      public com.google.protobuf.ByteString
          getStatIdBytes() {
        java.lang.Object ref = statId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          statId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stat_id = 14;</code>
       *
       * <pre>
       *统计标识
       * </pre>
       */
      public Builder setStatId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        statId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stat_id = 14;</code>
       *
       * <pre>
       *统计标识
       * </pre>
       */
      public Builder clearStatId() {
        bitField0_ = (bitField0_ & ~0x00000400);
        statId_ = getDefaultInstance().getStatId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string stat_id = 14;</code>
       *
       * <pre>
       *统计标识
       * </pre>
       */
      public Builder setStatIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        statId_ = value;
        onChanged();
        return this;
      }

      // optional int64 timekey = 15;
      private long timekey_ ;
      /**
       * <code>optional int64 timekey = 15;</code>
       *
       * <pre>
       *统计时间: 绝对秒数
       * </pre>
       */
      public boolean hasTimekey() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int64 timekey = 15;</code>
       *
       * <pre>
       *统计时间: 绝对秒数
       * </pre>
       */
      public long getTimekey() {
        return timekey_;
      }
      /**
       * <code>optional int64 timekey = 15;</code>
       *
       * <pre>
       *统计时间: 绝对秒数
       * </pre>
       */
      public Builder setTimekey(long value) {
        bitField0_ |= 0x00000800;
        timekey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timekey = 15;</code>
       *
       * <pre>
       *统计时间: 绝对秒数
       * </pre>
       */
      public Builder clearTimekey() {
        bitField0_ = (bitField0_ & ~0x00000800);
        timekey_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.frozen.pb.Dimensions)
    }

    static {
      defaultInstance = new Dimensions(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.frozen.pb.Dimensions)
  }

  public interface StatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .org.frozen.pb.Dimensions dims = 1;
    /**
     * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
     *
     * <pre>
     *统计维度
     * </pre>
     */
    boolean hasDims();
    /**
     * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
     *
     * <pre>
     *统计维度
     * </pre>
     */
    org.frozen.pb.ObjectStat.Dimensions getDims();
    /**
     * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
     *
     * <pre>
     *统计维度
     * </pre>
     */
    org.frozen.pb.ObjectStat.DimensionsOrBuilder getDimsOrBuilder();

    // optional int64 add_cnt = 3;
    /**
     * <code>optional int64 add_cnt = 3;</code>
     *
     * <pre>
     *新对象数
     * </pre>
     */
    boolean hasAddCnt();
    /**
     * <code>optional int64 add_cnt = 3;</code>
     *
     * <pre>
     *新对象数
     * </pre>
     */
    long getAddCnt();

    // optional int64 modify_cnt = 4;
    /**
     * <code>optional int64 modify_cnt = 4;</code>
     *
     * <pre>
     *修改对象数
     * </pre>
     */
    boolean hasModifyCnt();
    /**
     * <code>optional int64 modify_cnt = 4;</code>
     *
     * <pre>
     *修改对象数
     * </pre>
     */
    long getModifyCnt();

    // optional int64 old_cnt = 5;
    /**
     * <code>optional int64 old_cnt = 5;</code>
     *
     * <pre>
     *旧对象数
     * </pre>
     */
    boolean hasOldCnt();
    /**
     * <code>optional int64 old_cnt = 5;</code>
     *
     * <pre>
     *旧对象数
     * </pre>
     */
    long getOldCnt();
  }
  /**
   * Protobuf type {@code org.frozen.pb.Stat}
   *
   * <pre>
   *对象统计值
   * </pre>
   */
  public static final class Stat extends
      com.google.protobuf.GeneratedMessage
      implements StatOrBuilder {
    // Use Stat.newBuilder() to construct.
    private Stat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Stat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Stat defaultInstance;
    public static Stat getDefaultInstance() {
      return defaultInstance;
    }

    public Stat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Stat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.frozen.pb.ObjectStat.Dimensions.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = dims_.toBuilder();
              }
              dims_ = input.readMessage(org.frozen.pb.ObjectStat.Dimensions.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dims_);
                dims_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              addCnt_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              modifyCnt_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              oldCnt_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.frozen.pb.ObjectStat.internal_static_pb_ayena_Stat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.frozen.pb.ObjectStat.internal_static_pb_ayena_Stat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.frozen.pb.ObjectStat.Stat.class, org.frozen.pb.ObjectStat.Stat.Builder.class);
    }

    public static com.google.protobuf.Parser<Stat> PARSER =
        new com.google.protobuf.AbstractParser<Stat>() {
      public Stat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Stat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Stat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .org.frozen.pb.Dimensions dims = 1;
    public static final int DIMS_FIELD_NUMBER = 1;
    private org.frozen.pb.ObjectStat.Dimensions dims_;
    /**
     * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
     *
     * <pre>
     *统计维度
     * </pre>
     */
    public boolean hasDims() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
     *
     * <pre>
     *统计维度
     * </pre>
     */
    public org.frozen.pb.ObjectStat.Dimensions getDims() {
      return dims_;
    }
    /**
     * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
     *
     * <pre>
     *统计维度
     * </pre>
     */
    public org.frozen.pb.ObjectStat.DimensionsOrBuilder getDimsOrBuilder() {
      return dims_;
    }

    // optional int64 add_cnt = 3;
    public static final int ADD_CNT_FIELD_NUMBER = 3;
    private long addCnt_;
    /**
     * <code>optional int64 add_cnt = 3;</code>
     *
     * <pre>
     *新对象数
     * </pre>
     */
    public boolean hasAddCnt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 add_cnt = 3;</code>
     *
     * <pre>
     *新对象数
     * </pre>
     */
    public long getAddCnt() {
      return addCnt_;
    }

    // optional int64 modify_cnt = 4;
    public static final int MODIFY_CNT_FIELD_NUMBER = 4;
    private long modifyCnt_;
    /**
     * <code>optional int64 modify_cnt = 4;</code>
     *
     * <pre>
     *修改对象数
     * </pre>
     */
    public boolean hasModifyCnt() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 modify_cnt = 4;</code>
     *
     * <pre>
     *修改对象数
     * </pre>
     */
    public long getModifyCnt() {
      return modifyCnt_;
    }

    // optional int64 old_cnt = 5;
    public static final int OLD_CNT_FIELD_NUMBER = 5;
    private long oldCnt_;
    /**
     * <code>optional int64 old_cnt = 5;</code>
     *
     * <pre>
     *旧对象数
     * </pre>
     */
    public boolean hasOldCnt() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 old_cnt = 5;</code>
     *
     * <pre>
     *旧对象数
     * </pre>
     */
    public long getOldCnt() {
      return oldCnt_;
    }

    private void initFields() {
      dims_ = org.frozen.pb.ObjectStat.Dimensions.getDefaultInstance();
      addCnt_ = 0L;
      modifyCnt_ = 0L;
      oldCnt_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, dims_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, addCnt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, modifyCnt_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(5, oldCnt_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dims_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, addCnt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, modifyCnt_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, oldCnt_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.frozen.pb.ObjectStat.Stat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.frozen.pb.ObjectStat.Stat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.frozen.pb.ObjectStat.Stat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.frozen.pb.ObjectStat.Stat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.frozen.pb.ObjectStat.Stat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.frozen.pb.ObjectStat.Stat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.frozen.pb.ObjectStat.Stat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.frozen.pb.ObjectStat.Stat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.frozen.pb.ObjectStat.Stat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.frozen.pb.ObjectStat.Stat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.frozen.pb.ObjectStat.Stat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.frozen.pb.Stat}
     *
     * <pre>
     *对象统计值
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.frozen.pb.ObjectStat.StatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.frozen.pb.ObjectStat.internal_static_pb_ayena_Stat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.frozen.pb.ObjectStat.internal_static_pb_ayena_Stat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.frozen.pb.ObjectStat.Stat.class, org.frozen.pb.ObjectStat.Stat.Builder.class);
      }

      // Construct using org.frozen.pb.ObjectStat.Stat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDimsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (dimsBuilder_ == null) {
          dims_ = org.frozen.pb.ObjectStat.Dimensions.getDefaultInstance();
        } else {
          dimsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        addCnt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        modifyCnt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        oldCnt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.frozen.pb.ObjectStat.internal_static_pb_ayena_Stat_descriptor;
      }

      public org.frozen.pb.ObjectStat.Stat getDefaultInstanceForType() {
        return org.frozen.pb.ObjectStat.Stat.getDefaultInstance();
      }

      public org.frozen.pb.ObjectStat.Stat build() {
        org.frozen.pb.ObjectStat.Stat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.frozen.pb.ObjectStat.Stat buildPartial() {
        org.frozen.pb.ObjectStat.Stat result = new org.frozen.pb.ObjectStat.Stat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (dimsBuilder_ == null) {
          result.dims_ = dims_;
        } else {
          result.dims_ = dimsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.addCnt_ = addCnt_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.modifyCnt_ = modifyCnt_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.oldCnt_ = oldCnt_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.frozen.pb.ObjectStat.Stat) {
          return mergeFrom((org.frozen.pb.ObjectStat.Stat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.frozen.pb.ObjectStat.Stat other) {
        if (other == org.frozen.pb.ObjectStat.Stat.getDefaultInstance()) return this;
        if (other.hasDims()) {
          mergeDims(other.getDims());
        }
        if (other.hasAddCnt()) {
          setAddCnt(other.getAddCnt());
        }
        if (other.hasModifyCnt()) {
          setModifyCnt(other.getModifyCnt());
        }
        if (other.hasOldCnt()) {
          setOldCnt(other.getOldCnt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.frozen.pb.ObjectStat.Stat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.frozen.pb.ObjectStat.Stat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .org.frozen.pb.Dimensions dims = 1;
      private org.frozen.pb.ObjectStat.Dimensions dims_ = org.frozen.pb.ObjectStat.Dimensions.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.frozen.pb.ObjectStat.Dimensions, org.frozen.pb.ObjectStat.Dimensions.Builder, org.frozen.pb.ObjectStat.DimensionsOrBuilder> dimsBuilder_;
      /**
       * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
       *
       * <pre>
       *统计维度
       * </pre>
       */
      public boolean hasDims() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
       *
       * <pre>
       *统计维度
       * </pre>
       */
      public org.frozen.pb.ObjectStat.Dimensions getDims() {
        if (dimsBuilder_ == null) {
          return dims_;
        } else {
          return dimsBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
       *
       * <pre>
       *统计维度
       * </pre>
       */
      public Builder setDims(org.frozen.pb.ObjectStat.Dimensions value) {
        if (dimsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dims_ = value;
          onChanged();
        } else {
          dimsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
       *
       * <pre>
       *统计维度
       * </pre>
       */
      public Builder setDims(
          org.frozen.pb.ObjectStat.Dimensions.Builder builderForValue) {
        if (dimsBuilder_ == null) {
          dims_ = builderForValue.build();
          onChanged();
        } else {
          dimsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
       *
       * <pre>
       *统计维度
       * </pre>
       */
      public Builder mergeDims(org.frozen.pb.ObjectStat.Dimensions value) {
        if (dimsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              dims_ != org.frozen.pb.ObjectStat.Dimensions.getDefaultInstance()) {
            dims_ =
              org.frozen.pb.ObjectStat.Dimensions.newBuilder(dims_).mergeFrom(value).buildPartial();
          } else {
            dims_ = value;
          }
          onChanged();
        } else {
          dimsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
       *
       * <pre>
       *统计维度
       * </pre>
       */
      public Builder clearDims() {
        if (dimsBuilder_ == null) {
          dims_ = org.frozen.pb.ObjectStat.Dimensions.getDefaultInstance();
          onChanged();
        } else {
          dimsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
       *
       * <pre>
       *统计维度
       * </pre>
       */
      public org.frozen.pb.ObjectStat.Dimensions.Builder getDimsBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDimsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
       *
       * <pre>
       *统计维度
       * </pre>
       */
      public org.frozen.pb.ObjectStat.DimensionsOrBuilder getDimsOrBuilder() {
        if (dimsBuilder_ != null) {
          return dimsBuilder_.getMessageOrBuilder();
        } else {
          return dims_;
        }
      }
      /**
       * <code>optional .org.frozen.pb.Dimensions dims = 1;</code>
       *
       * <pre>
       *统计维度
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.frozen.pb.ObjectStat.Dimensions, org.frozen.pb.ObjectStat.Dimensions.Builder, org.frozen.pb.ObjectStat.DimensionsOrBuilder> 
          getDimsFieldBuilder() {
        if (dimsBuilder_ == null) {
          dimsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.frozen.pb.ObjectStat.Dimensions, org.frozen.pb.ObjectStat.Dimensions.Builder, org.frozen.pb.ObjectStat.DimensionsOrBuilder>(
                  dims_,
                  getParentForChildren(),
                  isClean());
          dims_ = null;
        }
        return dimsBuilder_;
      }

      // optional int64 add_cnt = 3;
      private long addCnt_ ;
      /**
       * <code>optional int64 add_cnt = 3;</code>
       *
       * <pre>
       *新对象数
       * </pre>
       */
      public boolean hasAddCnt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 add_cnt = 3;</code>
       *
       * <pre>
       *新对象数
       * </pre>
       */
      public long getAddCnt() {
        return addCnt_;
      }
      /**
       * <code>optional int64 add_cnt = 3;</code>
       *
       * <pre>
       *新对象数
       * </pre>
       */
      public Builder setAddCnt(long value) {
        bitField0_ |= 0x00000002;
        addCnt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 add_cnt = 3;</code>
       *
       * <pre>
       *新对象数
       * </pre>
       */
      public Builder clearAddCnt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        addCnt_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 modify_cnt = 4;
      private long modifyCnt_ ;
      /**
       * <code>optional int64 modify_cnt = 4;</code>
       *
       * <pre>
       *修改对象数
       * </pre>
       */
      public boolean hasModifyCnt() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 modify_cnt = 4;</code>
       *
       * <pre>
       *修改对象数
       * </pre>
       */
      public long getModifyCnt() {
        return modifyCnt_;
      }
      /**
       * <code>optional int64 modify_cnt = 4;</code>
       *
       * <pre>
       *修改对象数
       * </pre>
       */
      public Builder setModifyCnt(long value) {
        bitField0_ |= 0x00000004;
        modifyCnt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 modify_cnt = 4;</code>
       *
       * <pre>
       *修改对象数
       * </pre>
       */
      public Builder clearModifyCnt() {
        bitField0_ = (bitField0_ & ~0x00000004);
        modifyCnt_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 old_cnt = 5;
      private long oldCnt_ ;
      /**
       * <code>optional int64 old_cnt = 5;</code>
       *
       * <pre>
       *旧对象数
       * </pre>
       */
      public boolean hasOldCnt() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 old_cnt = 5;</code>
       *
       * <pre>
       *旧对象数
       * </pre>
       */
      public long getOldCnt() {
        return oldCnt_;
      }
      /**
       * <code>optional int64 old_cnt = 5;</code>
       *
       * <pre>
       *旧对象数
       * </pre>
       */
      public Builder setOldCnt(long value) {
        bitField0_ |= 0x00000008;
        oldCnt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 old_cnt = 5;</code>
       *
       * <pre>
       *旧对象数
       * </pre>
       */
      public Builder clearOldCnt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        oldCnt_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.frozen.pb.Stat)
    }

    static {
      defaultInstance = new Stat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.frozen.pb.Stat)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ayena_Dimensions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_ayena_Dimensions_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_ayena_Stat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pb_ayena_Stat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021object_stat.proto\022\010pb.ayena\"\247\001\n\nDimens" +
      "ions\022\n\n\002c1\030\001 \001(\t\022\n\n\002c2\030\002 \001(\t\022\n\n\002c3\030\003 \001(\t" +
      "\022\n\n\002c4\030\004 \001(\t\022\n\n\002c5\030\005 \001(\t\022\n\n\002c6\030\006 \001(\t\022\n\n\002" +
      "c7\030\007 \001(\t\022\n\n\002c8\030\010 \001(\t\022\n\n\002c9\030\t \001(\t\022\013\n\003c10\030" +
      "\n \001(\t\022\017\n\007stat_id\030\016 \001(\t\022\017\n\007timekey\030\017 \001(\003\"" +
      "`\n\004Stat\022\"\n\004dims\030\001 \001(\0132\024.org.frozen.pb.Dimensi" +
      "ons\022\017\n\007add_cnt\030\003 \001(\003\022\022\n\nmodify_cnt\030\004 \001(\003" +
      "\022\017\n\007old_cnt\030\005 \001(\003B\014\n\010pb.ayenaH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_pb_ayena_Dimensions_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_pb_ayena_Dimensions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pb_ayena_Dimensions_descriptor,
              new java.lang.String[] { "C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10", "StatId", "Timekey", });
          internal_static_pb_ayena_Stat_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_pb_ayena_Stat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_pb_ayena_Stat_descriptor,
              new java.lang.String[] { "Dims", "AddCnt", "ModifyCnt", "OldCnt", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
